'use client';

import { useState } from 'react';
import Button from '@/components/common/Button';

interface GeneratedNode {
  id: string;
  label: string;
  type: 'System' | 'Component' | 'Human';
}

interface GeneratedEdge {
  from: string;
  to: string;
  direction: 'A_TO_B' | 'B_TO_A' | 'BIDIRECTIONAL';
}

interface GenerationResult {
  success: boolean;
  nodes: GeneratedNode[];
  edges: GeneratedEdge[];
  error?: string;
}

interface AIModelGeneratorProps {
  projectId: string;
  onImported?: () => Promise<void> | void;
}

export default function AIModelGenerator({ projectId, onImported }: AIModelGeneratorProps) {
  const [textInput, setTextInput] = useState('');
  const [isBusy, setIsBusy] = useState(false);
  const [result, setResult] = useState<GenerationResult | null>(null);
  const [error, setError] = useState('');
  const [showPreview, setShowPreview] = useState(false);

  const handleGenerate = async () => {
    if (!textInput.trim()) {
      setError('Please enter a system description.');
      return;
    }

    try {
      setIsBusy(true);
      setError('');
      setResult(null);

      const response = await fetch(`/api/projects/${projectId}/ai/model-from-text`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ systemDescription: textInput.trim() }),
      });

      const payload = (await response.json()) as Partial<GenerationResult> & { error?: string };
      if (!response.ok || !payload.success) {
        throw new Error(payload.error || 'Generation failed');
      }

      const normalizedResult: GenerationResult = {
        success: true,
        nodes: payload.nodes || [],
        edges: payload.edges || [],
      };
      setResult(normalizedResult);
      setShowPreview(true);
    } catch (generationError) {
      setError((generationError as Error).message);
    } finally {
      setIsBusy(false);
    }
  };

  const handleImportModel = async () => {
    if (!result?.success) {
      setError('No generated model available.');
      return;
    }

    try {
      setIsBusy(true);
      setError('');

      const generatedToPersistedNodeId = new Map<string, string>();

      for (const node of result.nodes) {
        const nodeResponse = await fetch(`/api/projects/${projectId}/nodes`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            name: node.label,
            category: node.type,
            description: 'Generated by AI model assistant',
          }),
        });

        if (!nodeResponse.ok) {
          const payload = (await nodeResponse.json().catch(() => ({}))) as { error?: string };
          throw new Error(payload.error || `Node "${node.label}" could not be imported`);
        }

        const persistedNode = (await nodeResponse.json()) as { id: string };
        generatedToPersistedNodeId.set(node.id, persistedNode.id);
      }

      for (const edge of result.edges) {
        const sourceNodeId = generatedToPersistedNodeId.get(edge.from);
        const targetNodeId = generatedToPersistedNodeId.get(edge.to);

        if (!sourceNodeId || !targetNodeId) {
          continue;
        }

        const edgeResponse = await fetch(`/api/projects/${projectId}/edges`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            sourceNodeId,
            targetNodeId,
            direction: edge.direction,
            name: 'AI generated connection',
            protocol: 'Generated',
          }),
        });

        if (!edgeResponse.ok) {
          const payload = (await edgeResponse.json().catch(() => ({}))) as { error?: string };
          throw new Error(payload.error || 'One or more edges could not be imported');
        }
      }

      setTextInput('');
      setResult(null);
      setShowPreview(false);
      if (onImported) {
        await onImported();
      }
    } catch (importError) {
      setError((importError as Error).message);
    } finally {
      setIsBusy(false);
    }
  };

  return (
    <div className="space-y-6">
      {error && <div className="rounded border border-red-600/40 bg-red-900/20 p-3 text-sm text-red-200">{error}</div>}

      <div className="space-y-3">
        <label className="block text-sm font-semibold text-white">System Description</label>
        <p className="mb-2 text-xs text-slate-400">
          Describe components and interactions in natural language. AI will generate a candidate model.
        </p>

        <textarea
          value={textInput}
          onChange={(event) => setTextInput(event.target.value)}
          placeholder="Example: SCADA system with one HMI, three PLCs, and bidirectional Ethernet links."
          className="h-32 w-full resize-none rounded-lg border border-slate-600 bg-slate-700/50 p-3 font-mono text-sm text-white placeholder-slate-500 focus:border-orange-400 focus:outline-none focus:ring-1 focus:ring-orange-400/20"
        />

        <div className="flex gap-2">
          <Button onClick={handleGenerate} disabled={isBusy || !textInput.trim()}>
            {isBusy ? 'Analyzing...' : 'Generate Model'}
          </Button>

          {result?.success && (
            <button
              onClick={() => setShowPreview((prev) => !prev)}
              className="rounded-lg bg-slate-700 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-slate-600"
              type="button"
            >
              {showPreview ? 'Hide Preview' : 'Show Preview'}
            </button>
          )}
        </div>
      </div>

      {showPreview && result?.success && (
        <div className="space-y-4 rounded-lg border border-slate-700 bg-slate-800/50 p-6">
          <h3 className="text-lg font-semibold text-white">Model Preview</h3>

          <div>
            <p className="mb-2 text-sm font-semibold text-slate-300">Components ({result.nodes.length})</p>
            <div className="grid grid-cols-1 gap-2 md:grid-cols-2">
              {result.nodes.map((node) => (
                <div key={node.id} className="rounded border-l-2 border-orange-400 bg-slate-700/50 px-3 py-2">
                  <p className="text-sm font-medium text-white">{node.label}</p>
                  <p className="text-xs text-slate-400">{node.type}</p>
                </div>
              ))}
            </div>
          </div>

          {result.edges.length > 0 && (
            <div>
              <p className="mb-2 text-sm font-semibold text-slate-300">Connections ({result.edges.length})</p>
              <div className="space-y-1 text-xs text-slate-300">
                {result.edges.map((edge, index) => (
                  <div key={`${edge.from}-${edge.to}-${index}`} className="font-mono">
                    {edge.from} {edge.direction === 'BIDIRECTIONAL' ? '<->' : '->'} {edge.to}
                  </div>
                ))}
              </div>
            </div>
          )}

          <div className="border-t border-slate-700 pt-4">
            <button
              onClick={handleImportModel}
              disabled={isBusy}
              className="w-full rounded-lg bg-gradient-to-r from-orange-500 to-yellow-500 px-4 py-2 font-semibold text-slate-900 transition-all hover:from-orange-600 hover:to-yellow-600 disabled:opacity-60"
              type="button"
            >
              {isBusy ? 'Importing...' : 'Import Into Project'}
            </button>
          </div>
        </div>
      )}

      <div className="rounded-lg border border-slate-600 bg-slate-700/30 p-4">
        <p className="mb-2 text-xs font-semibold text-slate-300">Example Inputs</p>
        <div className="space-y-2">
          <button
            onClick={() =>
              setTextInput(
                'SCADA system with central HMI, 3 PLC nodes, and Ethernet connections. HMI communicates bidirectionally with all PLCs.'
              )
            }
            className="block w-full rounded bg-slate-600/50 p-2 text-left text-xs text-slate-300 transition-colors hover:bg-slate-600"
            type="button"
          >
            SCADA Example
          </button>
          <button
            onClick={() =>
              setTextInput(
                'Office network with gateway server, two switches, and twenty workstations. Workstations connect through switches.'
              )
            }
            className="block w-full rounded bg-slate-600/50 p-2 text-left text-xs text-slate-300 transition-colors hover:bg-slate-600"
            type="button"
          >
            Network Example
          </button>
        </div>
      </div>
    </div>
  );
}
